### ISSUE TITLE
Hooking up KeyCloak

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-api-java#11]
Hooking into KeyCloak for authentication, but also to lookup Users, Roles and Permissions.

**Comment by KurtStam** [comment]
I think it may make sense to run it embedded into the swarm server, for now at least:

https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/security/keycloak_server.html
https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/security/keycloak.html

**Comment by jimmidyson** [comment]
We should run Keycloak externally rather than embedded. For now, we might have to use RH SSO rather than Keycloak community version as there is no community version available that runs on OpenShift properly...
