### ISSUE TITLE
Add generic list sorting feature

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-api-java#22]
The UI requires a feature to sort and filter lists. I think this maybe on searches. It'd make sense to come up with generic search and sort that we can hook into the REST api.

**Comment by jimmidyson** [comment]
This should be on all list requests (`GET` on resources, not a separate search operation), fields that are filterable/searchable will be dependent on the type being requested.

**Comment by jimmidyson** [comment]
Closing now - sorting is fixed #32.
