### ISSUE TITLE
Update test data

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-api-java#23]
I've since updated the dummy data a bit to add some of the associations using a generator tool, would be awesome if we could get this loading, as it also contains generated dummy form data which will show up in the create connection flow I'm hoping to get finished up.

**Comment by gashcrumb** [comment]
Link would help, here's the latest -> https://github.com/redhat-ipaas/ipaas-api/blob/master/src/data/fixtures/development.json

**Comment by gashcrumb** [comment]
@KurtStam FYI btw, otherwise the UI looks kinda lame without the embedded form config :-)

**Comment by gashcrumb** [comment]
@kahboom CC

**Comment by KurtStam** [comment]
@gashcrumb it looks like you have an id at the top level:

https://github.com/redhat-ipaas/ipaas-api/blob/master/src/data/fixtures/development.json#L20

I fixed that in my dataset, but you may want to fix that.
