### ISSUE TITLE
Support running outside of kubernetes

### ISSUE THREAD

**Issue by KurtStam** [redhat-ipaas/ipaas-api-java#30]
For what reason do we involve fmp during the build? I like running

mvn clean install

from the parent module to compile the whole thing but that requires a running k8s. Do we really need that?

**Comment by jimmidyson** [comment]
There is no requirement to have k8s running anywhere. I don't run anything & it works just fine. I do agree that it's a bit annoying output though so perhaps we go back to hiding it behind a profile as @iocanel did before. I'm really trying to use the f-m-p developer tooling as it is set up for other projects. If it's too invasive, then we should give them that feedback too.

**Comment by kintergration** [comment]
It is annoying and its also time consuming, that's I wanted docker images to be build only when explicitly specified.

**Comment by jimmidyson** [comment]
Reveal your true self @kintergration! Don't hide behind the alias! I guess that's you @KurtStam?

**Comment by iocanel** [comment]
@jimmidyson: lol no that's mine!

**Comment by jimmidyson** [comment]
So should we put fmp all behind a fabric8 profile then?

**Comment by jimmidyson** [comment]
@rhuss Do you find most people hide d-m-p behind a profile? Seems similar to me.

**Comment by rhuss** [comment]
You simply can remove the <executions> in the configuration so that it has to be called explicitely. That's the easiest way and most straight forward way.
