### ISSUE TITLE
CORS Accept OPTIONS Method

### ISSUE THREAD

**Issue by kahboom** [redhat-ipaas/ipaas-api-java#42]
Testing the API from a REST client works fine, but not via the Angular client. Angular automatically sets request methods as `OPTIONS` for its initial request, which results in the following error and no data:

```
XMLHttpRequest cannot load http://127.0.0.1:8080/connections. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access. The response had HTTP status code 404.
```

This can be resolved either from the API or the client, but it's easier to do from the API. In the API you'd have to accept this method. In the client you'd have to install a proxy package (namely, [this one](https://github.com/chimurai/http-proxy-middleware)) or use Angular 2's RequestOptionsArgs() for each request. For now I will use the proxy package since I'm pressed for time, but would really like to have this done from the API.

**Comment by KurtStam** [comment]
No worries @kahboom we will take care of this on the server side.

**Comment by jimmidyson** [comment]
That is standard browser behaviour for cross domain requests via the/fetch (it's called a preflight check) & should already be handled by our cors filter added in d8add1c. Are you using the latest version of the api server @kahboom?

**Comment by kahboom** [comment]
Right @jimmidyson I know that, which is why I was confused; but it was a minor error on my part. Got it all sorted out and this can be closed. :)
